### ISSUE TITLE
Add a Rest API for check multiple toggles in one call

### ISSUE THREAD

**Issue by alexandrenavarro** [ff4j/ff4j-spring-boot-starter-parent#137]
**Is your feature request related to a problem? Please describe.**
Today, in our client application, we have to check 43 toggles at startup, it costs to call one by one notably because some our users are not closed to the servers, the latency is not so good (not in the same region/continent sometimes). So we want to have on call for n feature toggles.

**Describe the solution you'd like**
Add a Api in FF4jResource like

    @ApiOperation(value = "Check feature toggles", response = Map::class)
    @ApiResponses(
            ApiResponse(code = 200, message = "Map of featureUId/flipped"),
            ApiResponse(code = 400, message = "Invalid parameter"))
    @PostMapping(value = [("/$OPERATION_CHECK")])
    fun check(@RequestBody featureUIDs: List<String>): ResponseEntity<Map<String,Boolean>> {
        val featureUIDToEnableMap = HashMap<String, Boolean>()
        for (featureUID in featureUIDs) {
            val status = ff4JServices.check(featureUID)
            featureUIDToEnableMap[featureUID] = status
        }
        return ResponseEntity(featureUIDToEnableMap, OK)
    }

See my sample fork https://github.com/alexandrenavarro/ff4j-spring-boot-starter-parent/blob/master/ff4j-spring-boot-web-api/src/main/kotlin/org/ff4j/spring/boot/web/api/resources/FF4jResource.kt

Tell me if you are ok with the API added.

**Describe alternatives you've considered**
I'm not sure if you prefer to have a POST with requestBody with a list inside or wrapper with a list inside in case we want to add some parameter in the future (as you prefer).
We can do also a get with the list as requestParamater but I don't think it is good solution because the size of url is limited and we will have errors when the number of featureUid will be to important.

**Additional context**

I also created a issue in ff4j for the equivalent https://github.com/ff4j/ff4j/issues/449

**Comment by alexandrenavarro** [comment]
Draft PR https://github.com/ff4j/ff4j-spring-boot-starter-parent/pull/138

**Comment by paul58914080** [comment]
Hello @alexandrenavarro ,

Thank you for the write up and the PR. I did have one question as to why not use `GET /ff4j/store/features` which gets all the features from the store which also has the details whether your feature is enable or not.

Refer [swagger documentation](https://ff4j.herokuapp.com/swagger-ui.html#/FeatureStore/getAllFeaturesUsingGET)

It gives a response something like below, through which I believe you can know from `enable` property your feature is enabled or not

```
[
  {
    "uid": "admin_feature",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "group": null,
    "flippingStrategy": null,
    "permissions": [],
    "customProperties": {},
    "enable": true
  },
  {
    "uid": "user_feature",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "group": null,
    "flippingStrategy": null,
    "permissions": [],
    "customProperties": {},
    "enable": false
  },
  {
    "uid": "permissions_feature",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "group": null,
    "flippingStrategy": null,
    "permissions": [],
    "customProperties": {},
    "enable": false
  },
  {
    "uid": "dashboard_feature",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "group": null,
    "flippingStrategy": null,
    "permissions": [],
    "customProperties": {},
    "enable": false
  },
  {
    "uid": "login_feature",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "group": null,
    "flippingStrategy": null,
    "permissions": [],
    "customProperties": {},
    "enable": false
  },
  {
    "uid": "homepage_feature",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "group": null,
    "flippingStrategy": null,
    "permissions": [],
    "customProperties": {},
    "enable": true
  }
]
```

**Comment by alexandrenavarro** [comment]
> Thank you for the write up and the PR. I did have one question as to why not use `GET /ff4j/store/features` which gets all the features from the store which also has the details whether your feature is enable or not.

@paul58914080 
It is not the same when you use strategy in a toggle. Typically, we use/develop a customStrategy to active by user, group of users, region to easily activate a user when a new feature is developped to have just one beta tester, the toggle can be enable=true in /ff4j/store/features but the api with /check/featureUId can be false.
It was the reason why we can't use the GET /ff4j/store/features . 
We can do what you said only when you don't use strategy on a toggle.

Is it clear?

**Comment by paul58914080** [comment]
Thank you for the details and clarification. Much clear :)

I will write some tests around your PR and merge the same. And as @clun mentioned I think Set<String> makes more sense.

What do you think ?

**Comment by alexandrenavarro** [comment]
Agreed to use Set, it makes more sense, I will change it. Concerning (integration) test, I saw nothing, I'm right? I saw some bdd but not really on the same part, is there somewhere some test I have to improve?

**Comment by alexandrenavarro** [comment]
I updated the PR, tell me, if you want some other modifications.

**Comment by paul58914080** [comment]
I will merge this.

There are tests written in bdd for integration test https://github.com/ff4j/ff4j-spring-boot-starter-parent/blob/master/ff4j-spring-boot-web-api/src/test/java/org/ff4j/spring/boot/web/api/resources/feature/FeatureStepDef.java

I will update the tests once I merge the PR. Thank you for your contribution :tada:
