### ISSUE TITLE
When upgrading from 1.8.12 to 1.8.13 spring security now autoconfigures

### ISSUE THREAD

**Issue by vandykej17** [ff4j/ff4j-spring-boot-starter-parent#304]
**Describe the bug**
When upgrading from `1.8.12` I expected it to be a fairly easy transition. but then realized some security had been enabled.  I read your release tag for `1.8.13` and saw the configs I needed to add to disable security but saw they all defaulted to false anyway. 

This entry in my app logs is where I first noticed something was happening.
```
11:38:45.422 [] [main] WARN  o.s.b.a.s.s.UserDetailsServiceAutoConfiguration - 
Using generated security password: 79e64159-cb4b-411d-a61a-f455e53397c1
This generated password is for development use only. Your security configuration must be updated before running your application in production.
```

After some digging, I realized this was not an FF4J thing but a spring-autoconfigure item.  Looking at the dependencies, I assume this stems from these dependencies that were added in `1.8.13`
```
+--- org.ff4j:ff4j-security-spring:1.8.13
|    |    |    +--- org.ff4j:ff4j-core:1.8.13
|    |    |    +--- org.springframework:spring-context:5.3.19 -> 5.3.23 (*)
|    |    |    +--- org.springframework.security:spring-security-core:5.3.10.RELEASE -> 5.7.4
|    |    |    |    +--- org.springframework.security:spring-security-crypto:5.7.4
|    |    |    |    +--- org.springframework:spring-aop:5.3.23 (*)
|    |    |    |    +--- org.springframework:spring-beans:5.3.23 (*)
|    |    |    |    +--- org.springframework:spring-context:5.3.23 (*)
|    |    |    |    +--- org.springframework:spring-core:5.3.23 (*)
|    |    |    |    \--- org.springframework:spring-expression:5.3.23 (*)
|    |    |    +--- org.springframework.security:spring-security-web:5.3.10.RELEASE -> 5.7.4
|    |    |    |    +--- org.springframework.security:spring-security-core:5.7.4 (*)
|    |    |    |    +--- org.springframework:spring-core:5.3.23 (*)
|    |    |    |    +--- org.springframework:spring-aop:5.3.23 (*)
|    |    |    |    +--- org.springframework:spring-beans:5.3.23 (*)
|    |    |    |    +--- org.springframework:spring-context:5.3.23 (*)
|    |    |    |    +--- org.springframework:spring-expression:5.3.23 (*)
|    |    |    |    \--- org.springframework:spring-web:5.3.23 (*)
|    |    |    \--- org.springframework.security:spring-security-config:5.3.10.RELEASE -> 5.7.4
|    |    |         +--- org.springframework.security:spring-security-core:5.7.4 (*)
|    |    |         +--- org.springframework:spring-aop:5.3.23 (*)
|    |    |         +--- org.springframework:spring-beans:5.3.23 (*)
|    |    |         +--- org.springframework:spring-context:5.3.23 (*)
|    |    |         \--- org.springframework:spring-core:5.3.23 (*)
```

**To Reproduce**
Create an application where you don't want spring security enabled and use ff4j `1.8.13`

**Expected behavior**
Spring security is not automatically enabled.

## Fix
To fix this, I had to disable the autoconfiguration of Spring Security, a very simple solution once I figured out what was the cause.
`@SpringBootApplication(exclude = org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration.class)`

## My Request
Can you add to the GH Release a note about this, so future devs can notice easily that these dependencies were added and don't struggle like I did? Thanks!

**Comment by paul58914080** [comment]
@vandykej17 , you are right about the auto configuration with spring security. I have updated the release notes about it. Thank you.
