### ISSUE TITLE
turn ff4j swagger on or off by configuration property

### ISSUE THREAD

**Issue by xucw** [ff4j/ff4j-spring-boot-starter-parent#34]
hi @paul58914080 ,
       
I found there is a Swagger config in ff4j-spring-boot-web-api component which will be included in ff4j-spring-boot-starter component. If an application that has a Swagger config depends on ff4j-spring-boot-starter component, the application cannot run normally. So, It is recommended that configuration properties be provided, The user decides whether to turn ff4j swagger on or off by the configuration property.

Looking forward to your reply

**Comment by paul58914080** [comment]
Hello @xucw ,

Not sure what do you mean by 

> If an application that has a Swagger config depends on ff4j-spring-boot-starter component, **the application cannot run normally**

Did you face any challenge. Can you explain how ?

Would having an annotated configuration like `@EnableFF4jSwagger` work

**Comment by paul58914080** [comment]
@xucw I have implemented an annotation @EnableFF4jSwagger. Also the [sample](https://github.com/ff4j/ff4j-spring-boot-starter-parent/tree/master/ff4j-spring-boot-sample) has been updated with this example. 

In a gist:
To enable you need to add the annotation @EnableFF4jSwagger, [example](https://github.com/ff4j/ff4j-spring-boot-starter-parent/blob/master/ff4j-spring-boot-sample/src/main/java/org/ff4j/sample/Application.java#L27)

You can still override the configuration as demonstrated in [example](https://github.com/ff4j/ff4j-spring-boot-starter-parent/blob/master/ff4j-spring-boot-sample/src/main/java/org/ff4j/sample/config/SwaggerConfig.java)

**Comment by xucw** [comment]
Thank you, Paul.




------------------ 原始邮件 ------------------
发件人: "Paul Williams"<notifications@github.com>;
发送时间: 2019年3月10日(星期天) 下午2:58
收件人: "ff4j/ff4j-spring-boot-starter-parent"<ff4j-spring-boot-starter-parent@noreply.github.com>;
抄送: "拾贝者"<281287945@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ff4j/ff4j-spring-boot-starter-parent] turn ff4j swagger on oroff by configuration property (#34)




@xucw I have implemented an annotation @EnableFF4jSwagger. Also the sample has been updated with this example.
 
In a gist:
 To enable you need to add the annotation @EnableFF4jSwagger, example
 
You can still override the configuration as demonstrated in example

**Comment by xucw** [comment]
Hi Paul,
         To enable I need to add the annotation @EnableFF4jSwagger, If I don't add the annotation 
@EnableFF4jSwagger, the FF4j swagger config is disabled?  Is it right?




------------------ 原始邮件 ------------------
发件人: "Paul Williams"<notifications@github.com>;
发送时间: 2019年3月10日(星期天) 下午2:58
收件人: "ff4j/ff4j-spring-boot-starter-parent"<ff4j-spring-boot-starter-parent@noreply.github.com>;
抄送: "拾贝者"<281287945@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ff4j/ff4j-spring-boot-starter-parent] turn ff4j swagger on oroff by configuration property (#34)




@xucw I have implemented an annotation @EnableFF4jSwagger. Also the sample has been updated with this example.
 
In a gist:
 To enable you need to add the annotation @EnableFF4jSwagger, example
 
You can still override the configuration as demonstrated in example

**Comment by xucw** [comment]
Hi Paul,
         I update the sample and use maven clean install, but can't run normally. the exception as follows:





and the full error is attached.




------------------ 原始邮件 ------------------
发件人: "Paul Williams"<notifications@github.com>;
发送时间: 2019年3月10日(星期天) 下午2:58
收件人: "ff4j/ff4j-spring-boot-starter-parent"<ff4j-spring-boot-starter-parent@noreply.github.com>;
抄送: "拾贝者"<281287945@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ff4j/ff4j-spring-boot-starter-parent] turn ff4j swagger on oroff by configuration property (#34)




@xucw I have implemented an annotation @EnableFF4jSwagger. Also the sample has been updated with this example.
 
In a gist:
 To enable you need to add the annotation @EnableFF4jSwagger, example
 
You can still override the configuration as demonstrated in example

**Comment by paul58914080** [comment]
> Hi Paul, I update the sample and use maven clean install, but can't run normally. the exception as follows: and the full error is attached.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Paul Williams"<notifications@github.com>; 发送时间: 2019年3月10日(星期天) 下午2:58 收件人: "ff4j/ff4j-spring-boot-starter-parent"<ff4j-spring-boot-starter-parent@noreply.github.com>; 抄送: "拾贝者"<281287945@qq.com>; "Mention"<mention@noreply.github.com>; 主题: Re: [ff4j/ff4j-spring-boot-starter-parent] turn ff4j swagger on oroff by configuration property (#34) @xucw I have implemented an annotation @EnableFF4jSwagger. Also the sample has been updated with this example. In a gist: To enable you need to add the annotation @EnableFF4jSwagger, example You can still override the configuration as demonstrated in example — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Not sure how you have the sample. And not sure what is the error.

Can you provide a gist of what you did and I can try and see if I can re-produce the issue

**Comment by xucw** [comment]
Hi Paul,


         I have updated the sample from GitHub you provided, and I do the action as follow:
1. mvn clean
2. mvn install
3. run as Spring Boot App


Before I update the sample, I do the same action, and the sample can run normally and no error,
But I updated the sample yesterday, the sample can't run normally. the error is attached.




------------------ 原始邮件 ------------------
发件人: "Paul Williams"<notifications@github.com>;
发送时间: 2019年3月11日(星期一) 中午1:47
收件人: "ff4j/ff4j-spring-boot-starter-parent"<ff4j-spring-boot-starter-parent@noreply.github.com>;
抄送: "拾贝者"<281287945@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ff4j/ff4j-spring-boot-starter-parent] turn ff4j swagger on oroff by configuration property (#34)



 
Hi Paul, I update the sample and use maven clean install, but can't run normally. the exception as follows: and the full error is attached.
 …
 ------------------ 原始邮件 ------------------ 发件人: "Paul Williams"notifications@github.com; 发送时间: 2019年3月10日(星期天) 下午2:58 收件人: "ff4j/ff4j-spring-boot-starter-parent"ff4j-spring-boot-starter-parent@noreply.github.com; 抄送: "拾贝者"281287945@qq.com; "Mention"mention@noreply.github.com; 主题: Re: [ff4j/ff4j-spring-boot-starter-parent] turn ff4j swagger on oroff by configuration property (#34) @xucw I have implemented an annotation @EnableFF4jSwagger. Also the sample has been updated with this example. In a gist: To enable you need to add the annotation @EnableFF4jSwagger, example You can still override the configuration as demonstrated in example — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
  
Not sure how you have the sample. And not sure what is the error.
 
Can you provide a gist of what you did and I can try and see if I can re-produce the issue

**Comment by paul58914080** [comment]
Hello,

Could you please help me with an attachment. I am clueless with what error you are facing

**Comment by xucw** [comment]
Hi,


The error is attached in my last reply. Didn't you received the attachment?
The full error as follow:



Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
 
[2m2019-03-11 11:23:28.215[0;39m [31mERROR[0;39m [35m89765[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.boot.SpringApplication              [0;39m [2m:[0;39m Application run failed
 


 
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: @Configuration class 'FF4JConfiguration' may not be final. Remove the final modifier to continue.
 
Offending resource: class path resource [org/ff4j/spring/boot/autoconfigure/FF4JConfiguration.class]
 
	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:72) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
 
	at org.springframework.context.annotation.ConfigurationClass.validate(ConfigurationClass.java:217) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
 
	at org.springframework.context.annotation.ConfigurationClassParser.validate(ConfigurationClassParser.java:211) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
 
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:317) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
 
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
 
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:271) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
 
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:91) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
 
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:692) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
 
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:530) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
 
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
 
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
 
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230) [spring-boot-2.0.8.RELEASE.jar:2.0.8.RELEASE]
 
	at org.ff4j.sample.Application.main(Application.java:28) [classes/:na]
 











------------------ 原始邮件 ------------------
发件人: "Paul Williams"<notifications@github.com>;
发送时间: 2019年3月12日(星期二) 上午9:20
收件人: "ff4j/ff4j-spring-boot-starter-parent"<ff4j-spring-boot-starter-parent@noreply.github.com>;
抄送: "拾贝者"<281287945@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ff4j/ff4j-spring-boot-starter-parent] turn ff4j swagger on oroff by configuration property (#34)



Hello,
 
 Could you please help me with an attachment. I am clueless with what error you are facing

**Comment by paul58914080** [comment]
Hello @xucw ,

I am still unable to re-produce the issue. Can you confirm me which is the jdk you are using? 

As a workaround, can you try to declare a new `FF4JConfiguration` in your application which will override ?

In the mean time I will make `FF4JConfiguration` not final

**Comment by paul58914080** [comment]
I did a double check, and I do have included the plugin to open all

https://github.com/ff4j/ff4j-spring-boot-starter-parent/blob/master/pom.xml#L317-L323

I even checked the jar content and it was not final

**Comment by xucw** [comment]
Hi Paul,


I just need a Swagger switch. In fact, before updating the sample, I can run normally in my computer. So, I don't think the problem has anything to do with JDK version. My colleagues have
re-produce the issue.


By the way, My JDK version is 1.8.







------------------ 原始邮件 ------------------
发件人: "Paul Williams"<notifications@github.com>;
发送时间: 2019年3月12日(星期二) 晚上11:39
收件人: "ff4j/ff4j-spring-boot-starter-parent"<ff4j-spring-boot-starter-parent@noreply.github.com>;
抄送: "拾贝者"<281287945@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ff4j/ff4j-spring-boot-starter-parent] turn ff4j swagger on oroff by configuration property (#34)




Hello @xucw ,
 
I am still unable to re-produce the issue. Can you confirm me which is the jdk you are using?
 
As a workaround, can you try to declare a new FF4JConfiguration in your application which will override ?
 
In the mean time I will make FF4JConfiguration not final

**Comment by paul58914080** [comment]
Hello @xucw ,

Can you please confirm me the steps you have executed in the same order

### Step 1: 
On the main project **ff4j-spring-boot-starter-parent** you have run `mvn clean install`

### Step 2: 
On the sample project **ff4j-spring-boot-starter-parent/ff4j-spring-boot-sample** you have run `mvn clean install`

### Step 3: 
If you are running with an IDE dont forget to reimport the dependencies. Boot **ff4j-spring-boot-starter-parent/ff4j-spring-boot-sample** with `mvn spring-boot:run` . 

> PS: the parent and sample are two different projects though the sample is within the parent. If you notice, the parent pom you wont find the sample module.

**Comment by paul58914080** [comment]
Hello @xucw ,

Do you confirm you did the same steps and were able to re-produce. I tried to re-produce but I am not able to.

**Comment by paul58914080** [comment]
Hello @xucw ,

I am assuming this worked.

**Comment by paul58914080** [comment]
Hello @xucw ,

I am assuming it did work(no response). Closing the issue.
