### ISSUE TITLE
Would you please remove banner for ff4j

### ISSUE THREAD

**Issue by HaojunRen** [ff4j/ff4j-spring-boot-starter-parent#60]
I don't think that it is adding the banner of ff4j to custmon service side is a good idea, sometime people prefer to see the spring boot version with origin spring boot banner. Or you can add a config just like 'ff4j.banner.enabled=false' to close the banner. Thanks very much!

**Comment by paul58914080** [comment]
Hello,

As this is a ff4j spring boot starter for it has its own banner. However thanks to spring, they do provide you customization to show which spring boot version. To do so you can have a custom banner and have properties like `${spring-boot.version}`

Maybe the following link might help you : https://www.concretepage.com/spring-boot/spring-boot-custom-banner-example

**Comment by paul58914080** [comment]
Hello @HaojunRen ,

I hope I have answered the question. I will be closing this issue.

**Comment by zhangshity** [comment]
I just want to close ff4j own banner in springboot......... I don't want to emphasize that I'm using ff4j by a huge banner....

> Hello,
> 
> As this is a ff4j spring boot starter for it has its own banner. However thanks to spring, they do provide you customization to show which spring boot version. To do so you can have a custom banner and have properties like `${spring-boot.version}`
> 
> Maybe the following link might help you: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-spring-application.html#boot-features-banner

I just want to close ff4j own banner in springboot......... I don't want to emphasize that I'm using ff4j by a huge banner....
