### ISSUE TITLE
would you please add a control to enable/disable ff4j-spring-boot-starter?

### ISSUE THREAD

**Issue by HaojunRen** [ff4j/ff4j-spring-boot-starter-parent#61]
As title

**Comment by paul58914080** [comment]
Not really needed, if you exclude through the auto-configuration (spring-boot feature)

```java
@SpringBootApplication(exclude = {FF4JConfiguration.class})
```

**Comment by paul58914080** [comment]
> As title

Thank you @HaojunRen for this question. There are templates added in this repository for Bug reporting and new feature. It helps us streamline and also get more information when you report them. Next time request you to please use the template.

**Comment by HaojunRen** [comment]
Thanks. But i dont think it is a perfect solution, because users must modify their code。It is better to add @ConditonOnProperty to your FF4jConfiguration, such as ffj.enabled.

Another suggestion is please  format FF4J and FF4j to the same one

**Comment by paul58914080** [comment]
I dont understand what is the problem. You could as well use the property

```yml
spring.autoconfigure.exclude=org.ff4j.spring.boot.autoconfigure. FF4JConfiguration
```

**Comment by paul58914080** [comment]
Hello @HaojunRen ,

I hope I have answered the question. I will be closing this issue.
