### ISSUE TITLE
ff4j-store-redis to support Jedis 3.1.0

### ISSUE THREAD

**Issue by VidyasagarGayakawad** [ff4j/ff4j-spring-boot-starter-parent#72]
I am using spring boot version. - 2.2.1.RELEASE. application uses redis as a database so I have dependency on org.springframework.data -> spring-data-redis with version 2.2.1.RELEASE which uses Jedis 3.1.0 version otherwise it fails to make a Jedis connection.

Now my application has a dependency on ff4j-store-redis which has a latest version 1.8.2 and can use Jedis 2.10.0 not the 3.1.0 hence, I am unable to use ff4j-store-redis with spring boot 2.2.1.RELEASE.

ERROR -

Caused by: java.lang.ClassNotFoundException: redis.clients.util.Pool

**Comment by paul58914080** [comment]
I am not sure if this has anything to do with **ff4j-spring-boot-starter-parent** project. You are raising issue in the wrong project. This issue is pertaining to **ff4j** and hence you would have to raise it at https://github.com/ff4j/ff4j/issues.

**Comment by clun** [comment]
I am not surprised as the dependencies aging. Sounds like Jedis 2.x => 3.x introduced breaking changes. I can create the ticket in the core ff4j repo but the you will loose track VidyasagarGayakawad, so please create the issue.

I will have a look it should not be difficult to upgrade (single class to update) and I am back in the game.

**Comment by VidyasagarGayakawad** [comment]
Sure, let me open a new issue at https://github.com/ff4j/ff4j/issues. Thank you for your help..!
